package org.mpilone.vaadin.upload.plupload.shared;

import com.vaadin.shared.communication.ServerRpc;

/**
 * The remote procedure call interface which allows calls from the client side
 * to the server. For the most part these methods map to the events generated by
 * the Plupload JavaScript component.
 *
 * @author mpilone
 */
public interface PluploadServerRpc extends ServerRpc {
  void onUploadFile(String id, String name, int contentLength);

  void onError(String id, String name, String contentType,
      int contentLength, Integer errorCode, String errorReason);

  void onFileUploaded(String id, String name, int contentLength);

  void onInit(String runtime);

  void onProgress(String id, String name, int uploadedBytes, int totalBytes);

  void onStateChanged(int state);
}
